const COLORS = ['orange', 'gold', 'blue', 'purple', 'green', 'pink'];

function sanitizeRoom(value = '') {
  return String(value).replace(/[^A-Za-z0-9]/g, '').slice(0, 8).toUpperCase();
}

function renderColorClashController({ roomCode = '' } = {}) {
  const safeRoom = sanitizeRoom(roomCode);
  const swatches = COLORS.map((color, index) =>
    `<button class="swatch ${index === 0 ? 'selected' : ''}" type="button" data-color="${color}" aria-label="${color}" onclick="selectColor('${color}')"></button>`
  ).join('');

  return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#06110e"><title>TN Game Color Clash</title><style>
:root{color-scheme:dark;--orange:#f97316;--gold:#ffd54f;--blue:#3b82f6;--purple:#a855f7;--green:#22c55e;--pink:#ec4899;--panel:#0b1e18;--muted:#a7bdb5}*{box-sizing:border-box}body{font-family:system-ui,-apple-system,sans-serif;background:#06110e;color:#fff;margin:0;min-height:100vh;padding:calc(24px + env(safe-area-inset-top)) 22px calc(28px + env(safe-area-inset-bottom))}main{max-width:680px;margin:auto}.brand{color:var(--orange);font-weight:950}h1{font-size:clamp(34px,8vw,58px);line-height:1.03;margin:0 0 14px}.version{color:#739b8e;font-size:14px;font-weight:900;letter-spacing:.12em;margin-bottom:24px}.card{background:var(--panel);border:1px solid #21483c;border-radius:26px;padding:22px;box-shadow:0 20px 50px #0007}h2{font-size:clamp(28px,7vw,44px);margin:0 0 10px}p{color:var(--muted);line-height:1.5}label{display:block;color:var(--muted);font-weight:800;margin:14px 0 7px}input,button{font:inherit;border-radius:16px;border:1px solid #27604c}input{width:100%;padding:17px;background:#081712;color:#fff;font-size:20px}button{background:var(--orange);color:#fff;font-weight:900;padding:17px;cursor:pointer}.swatches{display:flex;gap:12px;flex-wrap:wrap;margin:12px 0 22px}.swatch{width:58px;height:58px;border-radius:50%;padding:0;border:4px solid transparent}.swatch.selected{border-color:#fff;box-shadow:0 0 0 3px #21483c}.swatch[data-color=orange],.card-color-orange{background:var(--orange)}.swatch[data-color=gold],.card-color-gold{background:var(--gold);color:#17200c}.swatch[data-color=blue],.card-color-blue{background:var(--blue)}.swatch[data-color=purple],.card-color-purple{background:var(--purple)}.swatch[data-color=green],.card-color-green{background:var(--green)}.swatch[data-color=pink],.card-color-pink{background:var(--pink)}.join,.draw{width:100%;font-size:22px}.status{margin-top:16px;min-height:24px;color:#7fd5b3;font-weight:800}.game-badge{display:inline-block;background:#123126;border:1px solid #27604c;border-radius:999px;padding:8px 12px;color:#7fd5b3;font-weight:900;margin-bottom:18px}.hidden{display:none}.score{display:flex;justify-content:space-between;gap:12px;background:#081712;border:1px solid #21483c;border-radius:18px;padding:14px;margin:12px 0}.discard{display:flex;align-items:center;justify-content:center;width:120px;height:160px;border-radius:20px;margin:18px auto;font-size:42px;font-weight:950;box-shadow:0 15px 35px #0008}.hand{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.play-card{min-height:110px;font-size:34px;border:4px solid #ffffff44;box-shadow:0 12px 25px #0007}.play-card:disabled{opacity:.42}.turn{font-size:28px;font-weight:950;text-align:center;margin:10px 0}.message{text-align:center;color:var(--muted);font-weight:800}</style></head><body><main><div class="brand">TN GAME</div><h1>COLOR CLASH</h1><div class="version">PHONE CONTROLLER v3.1 FIRST PLAYABLE ROUND</div>
<section id="joinPanel" class="card"><div class="game-badge">COLOR CLASH ROOM</div><h2>Join Color Clash</h2><p>Match the current color or number. First player to empty their hand wins.</p><label for="room">Room code</label><input id="room" maxlength="8" value="${safeRoom}" autocomplete="off"><label for="name">Player name</label><input id="name" maxlength="18" placeholder="Your name" autocomplete="name"><label>Choose your color</label><div class="swatches">${swatches}</div><button class="join" type="button" onclick="joinGame()">JOIN COLOR CLASH</button><div class="status" id="joinStatus"></div></section>
<section id="gamePanel" class="card hidden"><div class="game-badge">COLOR CLASH LIVE</div><h2 id="playerHeading">Your hand</h2><div class="score" id="score"></div><div id="turn" class="turn">Waiting for players…</div><div id="discard" class="discard">?</div><div id="message" class="message"></div><div id="hand" class="hand"></div><button id="drawButton" class="draw" type="button" onclick="drawCard()">DRAW CARD</button><div class="status" id="gameStatus"></div></section>
</main><script>
let selectedColor='orange';let session=null;let pollTimer=null;
function selectColor(color){selectedColor=color;document.querySelectorAll('.swatch').forEach(button=>button.classList.toggle('selected',button.dataset.color===color));}
function esc(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function joinGame(){const room=document.getElementById('room').value.trim().toUpperCase();const name=document.getElementById('name').value.trim();const status=document.getElementById('joinStatus');if(room.length<4){status.textContent='Enter the room code shown on the TV.';return}if(name.length<2){status.textContent='Enter your player name.';return}status.textContent='Joining Color Clash…';try{const response=await fetch('/api/rooms/'+encodeURIComponent(room)+'/join',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,color:selectedColor,game:'color-clash'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not join');session={room,token:data.player.token,player:data.player};localStorage.setItem('tnGameColorClashSessionV31',JSON.stringify(session));openGame();}catch(error){status.textContent=error.message;}}
function openGame(){document.getElementById('joinPanel').classList.add('hidden');document.getElementById('gamePanel').classList.remove('hidden');document.getElementById('playerHeading').textContent=(session.player.name||'PLAYER')+' • YOUR HAND';poll();clearInterval(pollTimer);pollTimer=setInterval(poll,900);}
async function poll(){if(!session)return;try{const response=await fetch('/api/color-clash/rooms/'+encodeURIComponent(session.room)+'/player?token='+encodeURIComponent(session.token)+'&t='+Date.now());const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load game');render(data);}catch(error){document.getElementById('gameStatus').textContent=error.message;}}
function render(data){const discard=document.getElementById('discard');if(data.discard){discard.className='discard card-color-'+data.discard.color;discard.textContent=data.discard.value;}else{discard.className='discard';discard.textContent='?';}document.getElementById('turn').textContent=data.phase==='finished'?(data.winnerId===data.player.id?'YOU WIN!':'GAME OVER'):(data.isTurn?'YOUR TURN':(data.currentPlayerName+' IS PLAYING'));document.getElementById('message').textContent=data.lastMove||'';document.getElementById('score').innerHTML=data.players.map(p=>'<div><strong>'+esc(p.name)+'</strong><br>'+p.cardCount+' cards</div>').join('');const hand=document.getElementById('hand');hand.innerHTML='';data.hand.forEach((card,index)=>{const button=document.createElement('button');button.className='play-card card-color-'+card.color;button.textContent=card.value;button.disabled=!data.isTurn||data.phase!=='playing';button.onclick=()=>playCard(index);hand.appendChild(button);});document.getElementById('drawButton').disabled=!data.isTurn||data.phase!=='playing';document.getElementById('gameStatus').textContent=data.isTurn?'Play a matching color or number, or draw.':'Controls unlock on your turn.';}
async function action(kind,payload={}){const status=document.getElementById('gameStatus');status.textContent='Sending move…';try{const response=await fetch('/api/color-clash/rooms/'+encodeURIComponent(session.room)+'/'+kind,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:session.token,...payload})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Move failed');render(data);}catch(error){status.textContent=error.message;}}
function playCard(index){action('play',{index});}function drawCard(){action('draw');}
try{const saved=JSON.parse(localStorage.getItem('tnGameColorClashSessionV31')||'null');if(saved&&saved.room&&saved.token){session=saved;document.getElementById('room').value=saved.room;openGame();}}catch{}
</script></body></html>`;
}

module.exports = {
  id: 'color-clash',
  title: 'Color Clash',
  controllerPath: '/color-clash',
  renderController: renderColorClashController,
};
