<?php
namespace TNG_OS\Modules\Entities;

use TNG_OS\Core\Container;
use TNG_OS\Core\Module_Interface;

if (!defined('ABSPATH')) exit;

final class Quest_Pipeline_Stabilizer implements Module_Interface {
    private const BLUEPRINT_TYPE = 'tng_quest_blueprint';

    public function id(): string { return 'quest_pipeline_stabilizer'; }

    public function register(Container $container): void {
        $container->set('quest_pipeline_stabilizer', $this);

        // Replace any older handler with one idempotent, diagnostic-aware write path.
        remove_all_actions('admin_post_tng_qi_create');
        add_action('admin_post_tng_qi_create', [$this, 'create_blueprint'], 1);
    }

    public function boot(Container $container): void {}

    public function create_blueprint(): void {
        if (!current_user_can('manage_options')) {
            $this->fail('permission', 'Your account does not have permission to create quest blueprints.');
        }

        $nonce = isset($_POST['_wpnonce']) ? sanitize_text_field(wp_unslash($_POST['_wpnonce'])) : '';
        if ($nonce === '' || !wp_verify_nonce($nonce, 'tng_qi_create')) {
            $this->fail('nonce', 'The security token expired. Refresh Quest Intelligence and try again.');
        }

        $candidate_key = sanitize_text_field(wp_unslash($_POST['candidate_key'] ?? ''));
        if ($candidate_key === '') {
            $this->fail('missing_candidate', 'No quest candidate was submitted.');
        }

        $candidate = $this->candidate($candidate_key);
        if (!$candidate) {
            $this->fail('candidate_not_found', 'The quest candidate is no longer available. Regenerate candidates and try again.');
        }

        // Reuse an existing blueprint so repeated clicks never create duplicates.
        $existing = get_posts([
            'post_type' => self::BLUEPRINT_TYPE,
            'post_status' => ['draft', 'private', 'publish', 'pending'],
            'posts_per_page' => 1,
            'fields' => 'ids',
            'meta_key' => '_tng_quest_candidate_key',
            'meta_value' => $candidate_key,
        ]);

        if ($existing) {
            $this->success((int)$existing[0], true);
        }

        $post_id = wp_insert_post([
            'post_type' => self::BLUEPRINT_TYPE,
            'post_status' => 'draft',
            'post_title' => sanitize_text_field((string)($candidate['title'] ?? 'Untitled Quest Blueprint')),
            'post_content' => $this->blueprint_content($candidate),
        ], true);

        if (is_wp_error($post_id)) {
            $this->fail('insert_failed', $post_id->get_error_message());
        }

        update_post_meta($post_id, '_tng_quest_candidate_key', $candidate_key);
        update_post_meta($post_id, '_tng_quest_template', sanitize_key((string)($candidate['template'] ?? 'generated')));
        update_post_meta($post_id, '_tng_quest_entity_ids', array_values(array_map('sanitize_text_field', (array)($candidate['entity_ids'] ?? []))));
        update_post_meta($post_id, '_tng_quest_quality_score', absint($candidate['quality'] ?? 0));
        update_post_meta($post_id, '_tng_quest_estimated_xp', absint($candidate['xp'] ?? 0));
        update_post_meta($post_id, '_tng_quest_estimated_minutes', absint($candidate['minutes'] ?? 0));
        update_post_meta($post_id, '_tng_quest_summary', sanitize_textarea_field((string)($candidate['summary'] ?? '')));
        update_post_meta($post_id, '_tng_quest_status', 'blueprint');
        update_post_meta($post_id, '_tng_quest_pipeline_created_at', current_time('mysql', true));

        $this->success((int)$post_id, false);
    }

    private function candidate(string $key): ?array {
        $candidates = get_option('tng_quest_intelligence_candidates', []);
        foreach (is_array($candidates) ? $candidates : [] as $candidate) {
            if (is_array($candidate) && hash_equals((string)($candidate['key'] ?? ''), $key)) return $candidate;
        }
        return null;
    }

    private function blueprint_content(array $candidate): string {
        $lines = [
            'Quest generated by TN Game OS Quest Intelligence.',
            '',
            'Template: ' . sanitize_text_field((string)($candidate['template_label'] ?? $candidate['template'] ?? 'Generated Quest')),
            'Quality score: ' . absint($candidate['quality'] ?? 0) . '/100',
            'Estimated reward: ' . absint($candidate['xp'] ?? 0) . ' XP',
            'Estimated duration: ' . $this->duration_label(absint($candidate['minutes'] ?? 0)),
            '',
            'Proposed checkpoints:',
        ];

        foreach ((array)($candidate['entities'] ?? []) as $index => $entity) {
            if (!is_array($entity)) continue;
            $lines[] = ($index + 1) . '. ' . sanitize_text_field((string)($entity['title'] ?? 'Checkpoint')) . ' (' . sanitize_key((string)($entity['type'] ?? 'entity')) . ')';
        }

        $lines[] = '';
        $lines[] = 'Editorial notes:';
        foreach ((array)($candidate['reasons'] ?? []) as $reason) $lines[] = '- ' . sanitize_text_field((string)$reason);
        return implode("\n", $lines);
    }

    private function duration_label(int $minutes): string {
        if ($minutes < 60) return $minutes . ' min';
        $hours = round($minutes / 60, 1);
        return rtrim(rtrim(number_format($hours, 1, '.', ''), '0'), '.') . ' hr';
    }

    private function success(int $blueprint_id, bool $reused): void {
        $url = add_query_arg([
            'page' => 'tng-quest-blueprint-studio',
            'blueprint' => $blueprint_id,
            'pipeline' => $reused ? 'reused' : 'created',
        ], admin_url('admin.php'));

        wp_redirect($url, 303, 'TN Game OS');
        exit;
    }

    private function fail(string $code, string $message): void {
        set_transient('tng_quest_pipeline_error_' . get_current_user_id(), [
            'code' => sanitize_key($code),
            'message' => sanitize_text_field($message),
            'time' => current_time('mysql', true),
        ], 10 * MINUTE_IN_SECONDS);

        $url = add_query_arg([
            'page' => 'tng-quest-intelligence',
            'pipeline_error' => sanitize_key($code),
        ], admin_url('admin.php'));
        wp_redirect($url, 303, 'TN Game OS');
        exit;
    }
}
