import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:30|3[1-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:30|3[1-9]|[4-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-plan-readiness/);
assert.match(adventure,/data-tng-readiness-key/);
assert.match(adventure,/data-tng-readiness-count/);
assert.match(adventure,/\['conditions','reservations','route','gear'\]/);
assert.match(adventure,/Restore this adventure before updating readiness/);
assert.match(adventure,/Schedule this adventure before using the readiness checklist/);
assert.match(adventure,/planned_date !== \$previous_date\) unset\(\$library\[\$index\]\['readiness'\]/);
assert.match(adventure,/unset\(\$copy\['archived_at'\], \$copy\['planned_date'\], \$copy\['readiness'\], \$copy\['readiness_updated_at'\]/);
assert.match(client,/operation:'readiness'/);
assert.match(client,/data-tng-next-readiness/);
assert.doesNotMatch(client,/setInterval|Notification/);
assert.match(css,/tng-adventure-card__readiness/);
assert.match(css,/@media\(max-width:390px\)/);
console.log('TN Game OS 5.130.0 Adventure Readiness Checklist checks passed');
