import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.151\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.151\.0'\)/);
assert.match(module,/data-tng-prep-focus/);
assert.match(module,/data-tng-prep-priority aria-live="polite"/);
assert.match(client,/const nextIncompleteCheckFor =/);
assert.match(client,/\[data-tng-readiness-key\],\[data-tng-packing-key\]/);
assert.match(client,/priorityPrep = checkbox \? \{card:priority,checkbox\} : null/);
assert.match(client,/selectedFilter = 'needs-prep'/);
assert.match(client,/priorityPrep\.card\.scrollIntoView/);
assert.match(client,/priorityPrep\?\.checkbox\.focus\(\{preventScroll:true\}\)/);
assert.match(css,/tng-adventure-library__prep-focus/);
assert.match(css,/tng-adventure-card\.is-prep-focus/);
const focus=client.slice(client.indexOf("prepFocus?.addEventListener('click'"),client.indexOf('const adventurePacks ='));
assert.doesNotMatch(focus,/post\(|fetch\(|\.click\(\)|checked\s*=/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.151.0 Private Adventure Prep Focus passed');
