import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:32|3[3-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:32|3[3-9]|[4-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-plan-timing/);
assert.match(adventure,/data-tng-timing-start/);
assert.match(adventure,/data-tng-timing-finish/);
assert.match(adventure,/data-tng-timing-duration/);
assert.match(adventure,/\$finish_minutes=\$plan_start\+\$plan_duration/);
assert.match(adventure,/next day/);
assert.match(adventure,/data-tng-next-timing/);
assert.match(client,/const timing = nextCard\.querySelector/);
assert.match(client,/data-tng-next-timing/);
assert.match(css,/tng-adventure-card__timing/);
const timingClient=client.slice(client.indexOf('const timing = nextCard'),client.indexOf("nextBanner.querySelector('[data-tng-next-readiness]"));
assert.doesNotMatch(timingClient,/post\(|fetch\(|operation:/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.132.0 Adventure Timing Summary checks passed');
