import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:1[7-9]|[2-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:1[7-9]|[2-9]\d)\.\d+'\)/);
assert.match(adventure,/private static function completed_plans\(int \$user_id\): array/);
assert.match(adventure,/TNG_Past_Trips_UI::history\(\$user_id\)/);
assert.match(adventure,/\(\$source\['kind'\] \?\? ''\) !== 'saved_adventure'/);
assert.match(adventure,/\$completed_plans\[\$plan_id\]/);
assert.match(adventure,/\$completed_trip\?'Start again':'Start adventure'/);
assert.match(adventure,/View recap →/);
assert.match(adventure,/home_url\('\/recaps\/'\)/);
assert.match(css,/\.tng-adventure-card\.is-completed/);
assert.match(css,/\.tng-adventure-card__completed/);
assert.match(css,/@media\(max-width:390px\)/);
console.log('TN Game OS 5.117.0 Completed Saved Adventures safety checks passed');
