import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
assert.match(bootstrap,/Version:\s*5\.139\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.139\.0'\)/);
assert.match(offline,/const ADVENTURE_PACK_PREFIX='tng-adventure-pack-v1-'/);
assert.match(offline,/key\.match\(\/-pack-\(adventure-\[a-f0-9\]\{20\}\)\$\//);
assert.match(offline,/caches\.open\(ADVENTURE_PACK_PREFIX\+legacy\[1\]\)/);
assert.match(offline,/if\(await target\.match\(request\)\)continue/);
assert.match(offline,/target\.put\(request,response\.clone\(\)\)/);
assert.match(offline,/key\.startsWith\(ADVENTURE_PACK_PREFIX\)&&key\.endsWith\('-staging'\)/);
assert.match(offline,/caches\.open\(ADVENTURE_PACK_PREFIX\+id\)/);
assert.match(offline,/const liveName=ADVENTURE_PACK_PREFIX\+id/);
const activation=offline.slice(offline.indexOf("self.addEventListener('activate'"),offline.indexOf("self.addEventListener('fetch'"));
assert.doesNotMatch(activation,/fetch\(/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
console.log('TN Game OS 5.139.0 Release-Stable Offline Adventure checks passed');
