import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:34|3[5-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:34|3[5-9]|[4-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-upcoming-calendar/);
assert.match(adventure,/Export calendar \(\.ics\)/);
assert.match(client,/upcomingCalendar\.hidden = scheduleWindows\.length === 0/);
assert.match(client,/event\.target\.closest\('\[data-tng-upcoming-calendar\]'\)/);
assert.match(client,/scheduleWindows\.flatMap/);
assert.match(client,/PRODID:-\/\/The TN Game\/\/Upcoming Adventures\/\/EN/);
assert.match(client,/BEGIN:VEVENT/);
assert.match(client,/END:VEVENT/);
assert.match(client,/tn-game-upcoming-adventures\.ics/);
assert.match(client,/\.tng-adventure-card__print li/);
const exportStart=client.indexOf("const exportUpcoming =");
const exportBlock=client.slice(exportStart,client.indexOf("const calendar =",exportStart));
assert.doesNotMatch(exportBlock,/post\(|fetch\(|operation:|plan_id/);
assert.match(css,/tng-adventure-library__calendar-export/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.134.0 Upcoming Adventures Calendar Export checks passed');
