import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.1(?:26|2[7-9]|[3-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:26|2[7-9]|[3-9]\d)\.\d+'\)/);
assert.match(adventure,/data-plan-date=/);
assert.match(adventure,/data-plan-start=/);
assert.match(adventure,/data-plan-duration=/);
assert.match(adventure,/data-tng-plan-calendar>Add to calendar \(\.ics\)/);
assert.match(client,/BEGIN:VCALENDAR/);
assert.match(client,/DTSTART:/);
assert.match(client,/DTEND:/);
assert.match(client,/text\/calendar;charset=utf-8/);
assert.match(client,/URL\.revokeObjectURL/);
const calendarBlock=client.slice(client.indexOf('const calendar ='),client.indexOf('const clearDate ='));
assert.doesNotMatch(calendarBlock,/post\(|fetch\(|planId|plan_id|user|account/i);
assert.match(calendarBlock,/\.tng-adventure-card__print li/);
console.log('TN Game OS 5.126.0 Private Calendar Export checks passed');
