import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const active=read('tn-game-active-trip-ui.php');
const archive=read('tn-game-past-trips-ui.php');
const client=read('assets/js/past-trips.js');
const recaps=read('tn-game-adventure-recaps.php');
assert.match(bootstrap,/Version:\s*5\.116\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.116\.0'\)/);
assert.match(archive,/TNG_Trip_Data::progress_summary\(\$user_id\)/);
assert.match(archive,/\(int\)\$progress\['remaining'\] > 0/);
assert.match(archive,/'source' => \[/);
assert.match(archive,/'status'=>\$status/);
assert.match(archive,/do_action\('tng_os_trip_archived', \$user_id, \$trip\);\s*TNG_Trip_Data::reset\(\$user_id\);/s);
assert.match(active,/data-resolved="<\?php echo esc_attr\(\(string\)\$resolved\); \?>"/);
assert.match(active,/data-total="<\?php echo esc_attr\(\(string\)\$total\); \?>"/);
assert.match(client,/resolved === total/);
assert.match(client,/Finish adventure/);
assert.match(recaps,/\$reward = \$status === 'completed' \? self::post_xp\(\$id\) : 0/);
assert.match(recaps,/'skipped' => \$skipped_count/);
assert.match(recaps,/intentionally skipped/);
console.log('TN Game OS 5.116.0 Adventure Finish Handoff safety checks passed');
