import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/offline-mode.js');
const css=read('assets/css/offline-adventure-manager.css');
assert.match(bootstrap,/Version:\s*5\.1(?:43|4[4-9]|[5-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:43|4[4-9]|[5-9]\d)\.\d+'\)/);
assert.match(offline,/offline-adventure-manager\.css/);
assert.match(client,/const verifiedDate = pack\?\.verifiedAt/);
assert.match(client,/verified \$\{/);
assert.match(client,/Remove from device/);
assert.match(client,/window\.confirm\(/);
assert.match(client,/Your Saved Adventure will remain in your Explorer account/);
assert.match(client,/TNG_ADVENTURE_PACK_REMOVE/);
assert.match(client,/TNG_ADVENTURE_PACK_LIBRARY/);
assert.match(client,/renderAdventureLibrary\(response\.ok/);
assert.match(offline,/metadata\.delete\(adventureMetaUrl\(id\)\)/);
assert.match(css,/tng-offline-adventure__summary/);
assert.match(css,/@media\(max-width:620px\)/);
assert.doesNotMatch(client,/admin-ajax|wp-json|credentials:'same-origin'/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.143.0 Device Offline Adventure Management checks passed');
