import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/offline-mode.js');
const css=read('assets/css/offline-adventure-manager.css');
assert.match(bootstrap,/Version:\s*5\.144\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.144\.0'\)/);
assert.match(offline,/response\.clone\(\)\.blob\(\)/);
assert.match(offline,/packs\.push\(\{id,count:urls\.length,urls,bytes,/);
assert.match(offline,/const clearAdventureLibrary=async/);
assert.match(offline,/key\.startsWith\(ADVENTURE_PACK_PREFIX\)/);
assert.match(offline,/caches\.delete\(ADVENTURE_META_CACHE\)/);
assert.match(offline,/TNG_ADVENTURE_PACK_CLEAR/);
assert.match(offline,/data-tng-device-adventure-summary/);
assert.match(offline,/data-tng-device-adventure-clear/);
assert.match(client,/const formatBytes/);
assert.match(client,/totalBytes/);
assert.match(client,/Remove every cached Adventure Pack from this device/);
assert.match(client,/TNG_ADVENTURE_PACK_CLEAR/);
assert.match(css,/tng-offline-adventures__tools/);
const clearBlock=offline.slice(offline.indexOf('const clearAdventureLibrary='),offline.indexOf("if(data.type==='TNG_OFFLINE_PACK_STATUS'"));
assert.doesNotMatch(clearBlock,/\bPACK_PREFIX\+|STATIC_CACHE|PAGE_CACHE|fetch\(/);
assert.doesNotMatch(client,/admin-ajax|wp-json|setInterval|Notification/);
console.log('TN Game OS 5.144.0 Offline Adventure Storage Summary checks passed');
