import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.123\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.123\.0'\)/);
assert.match(adventure,/data-tng-adventure-reset/);
assert.match(client,/tng_saved_adventure_view_v1/);
assert.match(client,/window\.localStorage\.getItem/);
assert.match(client,/window\.localStorage\.setItem/);
assert.match(client,/window\.localStorage\.removeItem/);
assert.match(client,/allowedFilters = \['all','active','ready','completed','archived'\]/);
assert.match(client,/allowedSorts = \['recent','title','status'\]/);
assert.doesNotMatch(client,/localStorage[^\n]*(planId|plan_id|account|user)/i);
assert.match(css,/tng-adventure-library__reset/);
console.log('TN Game OS 5.123.0 Device View Preferences checks passed');
