import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const mapPhp=read('tn-game-map-ui.php');
const mapJs=read('assets/js/map-ui.js');
const mapCss=read('assets/css/map-ui.css');
assert.match(bootstrap,/Version:\s*5\.(?:11[3-9]|1[2-9][0-9]|[2-9][0-9]{2})\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.(?:11[3-9]|1[2-9][0-9]|[2-9][0-9]{2})\.\d+'\)/);
assert.match(adventure,/public static function map_overlay\(string \$plan_id\): array/);
assert.match(adventure,/if \(!is_user_logged_in\(\)\) return \[\]/);
assert.match(adventure,/get_post_status\(\$id\) !== 'publish'/);
assert.match(adventure,/add_query_arg\('adventure'/);
assert.match(mapPhp,/'adventure' => \$adventure/);
assert.match(mapPhp,/Saved Adventure route/);
assert.match(mapJs,/cfg\.adventure\?\.stops/);
assert.match(mapJs,/L\.polyline\(routePoints/);
assert.match(mapJs,/tng-adventure-map-marker/);
assert.match(mapCss,/\.tng-map-adventure-banner/);
assert.match(mapCss,/@media\(max-width:430px\)/);
console.log('TN Game OS 5.113.0 Saved Adventure Maps safety checks passed');
