import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.133\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.133\.0'\)/);
assert.match(adventure,/data-tng-conflict-summary/);
assert.match(adventure,/data-tng-plan-conflict/);
assert.match(adventure,/data-tng-conflict-detail/);
assert.match(client,/const scheduleWindows = cards\.map/);
assert.match(client,/card\.dataset\.planState === 'archived'/);
assert.match(client,/card\.dataset\.planDate < todayKey/);
assert.match(client,/plan\.start >= other\.end \|\| other\.start >= plan\.end/);
assert.match(client,/has-schedule-conflict/);
assert.match(client,/Review their times before starting/);
const conflictsBlock=client.slice(client.indexOf('const scheduleWindows'),client.indexOf('try {'));
assert.doesNotMatch(conflictsBlock,/post\(|fetch\(|operation:|window\.location/);
assert.match(css,/tng-adventure-library__conflicts/);
assert.match(css,/tng-adventure-card\.has-schedule-conflict/);
assert.doesNotMatch(client,/setInterval|serviceWorker|Notification/);
console.log('TN Game OS 5.133.0 Private Schedule Conflict Alerts checks passed');
