import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.136\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.136\.0'\)/);
assert.match(offline,/const adventureStatus=async packs/);
assert.match(offline,/expected\.length===saved\.length/);
assert.match(offline,/expected\.every\(url=>saved\.includes\(url\)\)/);
assert.match(offline,/installed\[id\]=\{count:saved\.length,current:/);
assert.match(client,/TNG_ADVENTURE_PACK_STATUS',packs:/);
assert.match(client,/info\?\.current !== false/);
assert.match(client,/Update available/);
assert.match(client,/needs-update/);
assert.match(css,/tng-adventure-card__offline\.needs-update/);
const statusBlock=offline.slice(offline.indexOf('const adventureStatus='),offline.indexOf("if(data.type==='TNG_OFFLINE_PACK_STATUS'"));
assert.doesNotMatch(statusBlock,/fetch\(|cache\.put|cache\.delete/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.136.0 Offline Adventure Pack Freshness checks passed');
