import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:29|[3-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:29|[3-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-next-map/);
assert.match(adventure,/data-tng-next-action/);
assert.match(client,/routeLink = nextCard\.querySelector/);
assert.match(client,/activeLink = nextCard\.querySelector/);
assert.match(client,/Start today's adventure/);
assert.match(client,/startButton\.click\(\)/);
assert.match(client,/window\.location\.assign\(activeLink\.href\)/);
assert.doesNotMatch(client,/operation:'quick_start'|operation:'resume'/);
assert.match(css,/tng-adventure-library__next-actions/);
console.log('TN Game OS 5.129.0 Next Adventure Quick Actions checks passed');
