import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.1(?:37|3[8-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:37|3[8-9]|[4-9]\d)\.\d+'\)/);
assert.match(offline,/const cacheEntries=async cache/);
assert.match(offline,/const writeEntries=async\(name,entries\)/);
assert.match(offline,/const stagingName=liveName\+'-staging'/);
assert.match(offline,/const previous=await cacheEntries\(await caches\.open\(liveName\)\)/);
assert.match(offline,/if\(failed\.length\|\|saved!==values\.length\)/);
assert.match(offline,/preserved:previous\.length/);
assert.match(offline,/await writeEntries\(liveName,previous\)/);
assert.match(offline,/credentials:'omit'/);
assert.match(offline,/X-TNG-Offline-Safe/);
const saveBlock=offline.slice(offline.indexOf("if(data.type==='TNG_ADVENTURE_PACK_SAVE'"));
assert.ok(saveBlock.indexOf('if(failed.length||saved!==values.length)')<saveBlock.indexOf('await caches.delete(liveName)'));
assert.match(client,/Update incomplete/);
assert.match(client,/previous screen/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.137.0 Failure-Safe Offline Pack Update checks passed');
