import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/offline-mode.js');
const css=read('assets/css/offline-mode.css');
assert.match(bootstrap,/Version:\s*5\.1(?:42|4[3-9]|[5-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:42|4[3-9]|[5-9]\d)\.\d+'\)/);
assert.match(offline,/const adventureLibrary=async/);
assert.match(offline,/key\.startsWith\(ADVENTURE_PACK_PREFIX\)/);
assert.match(offline,/urls,(?:bytes,)?verifiedAt:/);
assert.match(offline,/TNG_ADVENTURE_PACK_LIBRARY/);
assert.match(offline,/data-tng-device-adventures/);
assert.match(offline,/Public stop screens only · plan details stay private/);
assert.match(client,/const renderAdventureLibrary/);
assert.match(client,/url\.origin !== window\.location\.origin/);
assert.match(client,/document\.createElement\('a'\)/);
assert.match(client,/Saved Adventure \$\{packIndex \+ 1\}/);
assert.match(client,/device only/);
assert.match(client,/TNG_ADVENTURE_PACK_LIBRARY/);
assert.match(css,/tng-offline-adventures/);
assert.match(css,/@media\(max-width:620px\)/);
const libraryBlock=offline.slice(offline.indexOf('const adventureLibrary='),offline.indexOf("if(data.type==='TNG_OFFLINE_PACK_STATUS'"));
assert.doesNotMatch(libraryBlock,/fetch\(|wp-json|admin-ajax/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.142.0 Device-Local Offline Adventure Launcher checks passed');
