import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:4[8-9]|[5-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:4[8-9]|[5-9]\d)\.\d+'\)/);
assert.match(module,/data-plan-packed-count/);
assert.match(module,/data-tng-next-packing/);
assert.match(module,/data-tng-next-launch-progress/);
assert.match(module,/data-tng-next-launch-label/);
assert.match(client,/const updateNextLaunchStatus =/);
assert.match(client,/const complete = ready \+ packed/);
assert.match(client,/remaining === 0 \? 'Launch checks complete'/);
assert.match(client,/card\.dataset\.planPackedCount = String\(count\)/);
assert.match(client,/if \(card === nextCard\) updateNextLaunchStatus\(\)/);
assert.match(css,/tng-adventure-library__launch-status/);
const launchBlock=client.slice(client.indexOf('const updateNextLaunchStatus ='),client.indexOf('if (nextBanner && nextCard)'));
assert.doesNotMatch(launchBlock,/fetch\(|post\(|localStorage|admin-ajax|wp-json/);
const clickHandler=client.indexOf("root.addEventListener('click'");
const startBlock=client.slice(client.indexOf("const start =",clickHandler),client.indexOf("const button =",clickHandler));
assert.doesNotMatch(startBlock,/planReadyCount|planPackedCount|launch check/i);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.148.0 Next Adventure Launch Status passed');
