import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:4[7-9]|[5-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:4[7-9]|[5-9]\d)\.\d+'\)/);
assert.match(module,/data-tng-plan-packing/);
assert.match(module,/data-tng-packing-key/);
assert.match(module,/\$operation === 'packing'/);
assert.match(module,/\$allowed = \['water','layers','footwear','phone','tickets','safety'\]/);
assert.match(module,/Schedule this adventure before using its packing list/);
assert.match(module,/\['packing'\], \$library\[\$index\]\['packing_updated_at'\]/);
assert.match(module,/data-tng-print-packing/);
assert.match(module,/data-tng-print-stops/);
assert.match(client,/operation:'packing'/);
assert.match(client,/packing_key:packingCheckbox\.dataset\.tngPackingKey/);
assert.match(client,/data-tng-print-packing-count/);
assert.match(css,/tng-adventure-card__packing/);
const shareBlock=client.slice(client.indexOf("const share ="),client.indexOf("const start ="));
const calendarBlock=client.slice(client.indexOf("const calendar ="),client.indexOf("const clearDate ="));
assert.doesNotMatch(shareBlock,/packing/i);
assert.doesNotMatch(calendarBlock,/packing/i);
assert.match(calendarBlock,/querySelectorAll\('\[data-tng-print-stops\] li'\)/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.147.0 Private Adventure Packing Checklist passed');
