import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:5\d|[6-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:5\d|[6-9]\d)\.\d+'\)/);
assert.match(module,/data-tng-prep-overview/);
assert.match(module,/data-tng-prep-upcoming/);
assert.match(module,/data-tng-prep-needed/);
assert.match(module,/data-tng-prep-ready/);
assert.match(module,/data-tng-prep-priority/);
assert.match(client,/const updatePrepOverview =/);
assert.match(client,/card\.dataset\.planState !== 'archived' && card\.dataset\.planDate >= todayKey/);
assert.match(client,/const priority = \[\.\.\.needsPrep\]\.sort/);
assert.match(client,/10 - launchCountFor\(priority\)/);
assert.match(client,/filter\.click\(\)/);
assert.match(css,/tng-adventure-library__prep-overview/);
assert.match(css,/@media\(max-width:720px\).*tng-adventure-library__prep-overview\{align-items:stretch;flex-direction:column\}/s);
const overview=client.slice(client.indexOf('const updatePrepOverview ='),client.indexOf('const applyFilters ='));
assert.doesNotMatch(overview,/fetch\(|post\(|localStorage|admin-ajax|wp-json/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.150.0 Private Adventure Prep Overview passed');
