import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:35|3[6-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:35|3[6-9]|[4-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-adventure-offline/);
assert.match(adventure,/data-tng-offline-pack/);
assert.match(adventure,/data-tng-offline-urls/);
assert.match(adventure,/hash_hmac\('sha256',\$plan_id,wp_salt\('nonce'\)\)/);
assert.match(offline,/SAFE_POST_TYPES/);
assert.match(offline,/get_post_status\(get_queried_object_id\(\)\) === 'publish'/);
assert.match(offline,/TNG_ADVENTURE_PACK_STATUS/);
assert.match(offline,/TNG_ADVENTURE_PACK_SAVE/);
assert.match(offline,/TNG_ADVENTURE_PACK_REMOVE/);
assert.match(offline,/\^adventure-\[a-f0-9\]\{20\}\$/);
assert.match(offline,/credentials:'omit'/);
assert.match(offline,/response\.headers\.get\('X-TNG-Offline-Safe'\)==='1'/);
assert.match(offline,/\.slice\(0,12\)/);
assert.match(client,/navigator\.serviceWorker\.ready/);
assert.match(client,/TNG_ADVENTURE_PACK_SAVE/);
assert.match(client,/TNG_ADVENTURE_PACK_REMOVE/);
assert.match(client,/pack\.urls/);
assert.match(css,/tng-adventure-card__offline/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(offline,/request\.method===\s*['"]POST['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.135.0 Privacy-Safe Offline Adventure Packs checks passed');
