import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.146\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.146\.0'\)/);
assert.match(module,/Day-of Adventure Brief/);
assert.match(module,/data-tng-print-readiness-count/);
assert.match(module,/data-tng-print-readiness=/);
assert.match(module,/data-tng-print-notes/);
assert.match(module,/\$arrival\+=\$planner->visit_minutes/);
assert.match(module,/add_query_arg\('adventure',\$plan_id,home_url\('\/map\/'\)\)/);
assert.match(client,/printItem\.classList\.toggle\('is-ready'/);
assert.match(client,/printNotes\.querySelector\('p'\)\.textContent/);
assert.match(css,/tng-adventure-card__print-readiness/);
assert.match(css,/tng-adventure-card__print-notes/);
const printBlock=module.slice(module.indexOf('<section class="tng-adventure-card__print"'),module.indexOf('</section>',module.indexOf('<section class="tng-adventure-card__print"'))+10);
assert.doesNotMatch(printBlock,/wp_remote_|fetch\(|admin-ajax|wp-json/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.146.0 Day-of Adventure Brief passed');
