import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const tripData=read('tn-game-trip-data.php');
const trips=read('tn-game-trips-ui.php');
const library=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:1[4-9]|[2-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:1[4-9]|[2-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-plan-start/);
assert.match(adventure,/\$operation === 'start'/);
assert.match(adventure,/confirm_required/);
assert.match(adventure,/TNG_Trip_Data::replace/);
assert.match(adventure,/home_url\('\/trip-builder\/'\)/);
assert.match(tripData,/public static function replace\(array \$post_ids, int \$user_id, array \$source = \[\]\): array/);
assert.match(tripData,/delete_user_meta\(\$user_id, self::COMPLETED_META_KEY\)/);
assert.match(tripData,/SOURCE_META_KEY/);
assert.match(trips,/TNG_Trip_Data::(?:active_source|progress_summary)/);
assert.match(library,/window\.confirm/);
assert.match(library,/confirm_replace/);
assert.match(css,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
console.log('TN Game OS 5.114.0 Adventure Launch Handoff safety checks passed');
