import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.138\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.138\.0'\)/);
assert.match(offline,/const storageHeadroom=async/);
assert.match(offline,/self\.navigator\.storage\.estimate\(\)/);
assert.match(offline,/Math\.max\(8388608,Math\.ceil\(quota\*\.02\)\)/);
assert.match(offline,/error:'low-storage'/);
assert.match(offline,/preserved:previous\.length,storage/);
const saveBlock=offline.slice(offline.indexOf("if(data.type==='TNG_ADVENTURE_PACK_SAVE'"));
assert.ok(saveBlock.indexOf('if(!storage.ok)')<saveBlock.indexOf('await caches.delete(stagingName)'));
assert.ok(saveBlock.indexOf('if(!storage.ok)')<saveBlock.indexOf('const staging=await caches.open(stagingName)'));
assert.match(client,/result\.error === 'low-storage'/);
assert.match(client,/remove another offline pack first/);
assert.match(client,/previous screen/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.138.0 Offline Adventure Storage Guard checks passed');
