import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:20|2[1-9]|[3-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:20|2[1-9]|[3-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-adventure-sort/);
assert.match(adventure,/data-plan-updated=/);
assert.match(client,/sort\?\.value === 'title'/);
assert.match(client,/sort\?\.value === 'status'/);
assert.match(client,/stateOrder = \{active:0,ready:1,completed:2(?:,|\})/);
assert.match(client,/grid\.append\(card\)/);
assert.doesNotMatch(client,/operation:'sort'/);
assert.match(css,/tng-adventure-library__organizer select/);
console.log('TN Game OS 5.120.0 Saved Adventure Sorting checks passed');
