import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:31|3[2-9]|[4-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:31|3[2-9]|[4-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-plan-notes-panel/);
assert.match(adventure,/data-tng-plan-notes/);
assert.match(adventure,/textarea name="notes" maxlength="600"/);
assert.match(adventure,/\$operation === 'notes'/);
assert.match(adventure,/sanitize_textarea_field/);
assert.match(adventure,/mb_substr\(\$notes, 0, 600\)/);
assert.match(adventure,/Restore this adventure before updating its notes/);
assert.match(adventure,/\$copy\['notes'\]/);
assert.match(client,/operation:'notes'/);
assert.match(client,/data-tng-notes-count/);
assert.match(client,/notes\.value\.length/);
assert.match(css,/tng-adventure-card__notes/);
const printStart=adventure.indexOf('<section class="tng-adventure-card__print"');
const printBlock=adventure.slice(printStart,adventure.indexOf('</article>',printStart));
assert.doesNotMatch(printBlock,/\$notes|plan\['notes'\]/);
const shareBlock=client.slice(client.indexOf("const share ="),client.indexOf("const start ="));
assert.doesNotMatch(shareBlock,/notes|planning/i);
assert.doesNotMatch(client,/setInterval|serviceWorker|Notification/);
console.log('TN Game OS 5.131.0 Private Adventure Planning Notes checks passed');
