import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.153\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.153\.0'\)/);
assert.match(client,/const refreshPrepViews = \(\) =>/);
assert.match(client,/updatePrepOverview\(\);\n\s*if \(selectedFilter === 'needs-prep' \|\| selectedFilter === 'launch-ready' \|\| sort\?\.value === 'prep'\) applyFilters\(\)/);
assert.equal((client.match(/refreshPrepViews\(\);/g)||[]).length,2);
const helper=client.slice(client.indexOf('const refreshPrepViews ='),client.indexOf("search?.addEventListener"));
assert.doesNotMatch(helper,/post\(|fetch\(|checked\s*=|localStorage|\.click\(\)/);
const packingStart=client.indexOf("const packingCheckbox =");
const readinessStart=client.indexOf("const checkbox =",packingStart);
const packing=client.slice(packingStart,readinessStart);
const readiness=client.slice(readinessStart,client.indexOf("root.addEventListener('click'",readinessStart));
assert.match(packing,/refreshPrepViews\(\)/);
assert.match(readiness,/refreshPrepViews\(\)/);
assert.match(packing,/await post\(\{operation:'packing'/);
assert.match(readiness,/await post\(\{operation:'readiness'/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.153.0 Live Prep Priority Refresh passed');
