import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const tripData=read('tn-game-trip-data.php');
const trips=read('tn-game-trips-ui.php');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:1[5-9]|[2-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:1[5-9]|[2-9]\d)\.\d+'\)/);
assert.match(tripData,/public static function progress_summary\(int \$user_id = 0\): array/);
assert.match(tripData,/'remaining_ids' => \$remaining_ids/);
assert.match(tripData,/'skipped' => count\(\$skip_ids\)/);
assert.match(tripData,/'next_id' => \$remaining_ids \? \(int\) \$remaining_ids\[0\] : 0/);
assert.match(adventure,/\$active_plan_id/);
assert.match(adventure,/hash_equals\(\$active_plan_id,\(string\)\$plan\['id'\]\)/);
assert.match(adventure,/>Resume adventure</);
assert.match(adventure,/class="tng-adventure-card<\?php echo \$is_active\?' is-active':''; \?>"/);
assert.match(trips,/TNG_Trip_Data::progress_summary/);
assert.match(trips,/\$remaining === 0 \? 'Finish adventure' : 'Resume adventure'/);
assert.match(css,/\.tng-adventure-card\.is-active/);
assert.match(css,/@media\(max-width:390px\)/);
console.log('TN Game OS 5.115.0 Active Adventure Resume safety checks passed');
