import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.128\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.128\.0'\)/);
assert.match(adventure,/data-tng-next-adventure/);
assert.match(adventure,/data-tng-next-title/);
assert.match(adventure,/data-tng-next-countdown/);
assert.match(adventure,/data-tng-next-jump/);
assert.match(client,/nextCard = cards\.filter/);
assert.match(client,/daysAway === 0 \? 'Today'/);
assert.match(client,/daysAway === 1 \? 'Tomorrow'/);
assert.match(client,/scrollIntoView/);
assert.doesNotMatch(client.slice(client.indexOf('const nextBanner ='),client.indexOf('const post =')),/post\(|fetch\(/);
assert.match(css,/\.tng-adventure-library__next/);
assert.match(css,/\.tng-adventure-card\.is-next-up/);
console.log('TN Game OS 5.128.0 Next Adventure Dashboard checks passed');
