import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:24|2[5-9]|[3-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:24|2[5-9]|[3-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-plan-print>(?:Print \/ save PDF|Day-of brief \/ PDF)/);
assert.match(adventure,/class="tng-adventure-card__print"/);
assert.match(adventure,/\$print_ids=array_slice\(\(array\)\$plan\['ids'\],0,12\)/);
assert.match(adventure,/start_minutes/);
assert.match(adventure,/buffer_minutes/);
assert.match(client,/event\.target\.closest\('\[data-tng-plan-print\]'\)/);
assert.match(client,/window\.print\(\)/);
assert.match(client,/window\.addEventListener\('afterprint', cleanupPrint\)/);
const printBlock=client.slice(client.indexOf("const print ="),client.indexOf("const archive ="));
assert.doesNotMatch(printBlock,/post\(|fetch\(|planId|plan_id/);
assert.match(css,/@media print/);
assert.match(css,/\.is-print-target/);
console.log('TN Game OS 5.124.0 Printable Saved Adventures checks passed');
