import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:19|[2-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:19|[2-9]\d)\.\d+'\)/);
assert.match(adventure,/data-tng-adventure-search/);
assert.match(adventure,/data-tng-adventure-filter="active"/);
assert.match(adventure,/data-plan-state=/);
assert.match(client,/const applyFilters/);
assert.match(client,/card\.dataset\.planState/);
assert.match(client,/card\.textContent\.toLocaleLowerCase/);
assert.match(client,/card\.hidden/);
assert.doesNotMatch(client,/operation:'filter'|operation:'search'/);
assert.match(css,/@media\(max-width:390px\).*tng-adventure-library__filters/s);
console.log('TN Game OS 5.119.0 Saved Adventure Organizer checks passed');
