import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.149\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.149\.0'\)/);
assert.match(module,/data-tng-adventure-filter="needs-prep"/);
assert.match(module,/data-tng-adventure-filter="launch-ready"/);
assert.match(module,/data-tng-plan-launch-score/);
assert.match(module,/data-tng-plan-launch-progress/);
assert.match(client,/const updateCardLaunchStatus =/);
assert.match(client,/selectedFilter === 'needs-prep' \? upcoming && launchCount < 10/);
assert.match(client,/selectedFilter === 'launch-ready' \? upcoming && launchCount === 10/);
assert.match(client,/card\.dataset\.planState !== 'archived' && card\.dataset\.planDate >= todayKey/);
assert.match(client,/updateCardLaunchStatus\(card\)/);
assert.match(css,/tng-adventure-card__launch-score/);
const helper=client.slice(client.indexOf('const updateCardLaunchStatus ='),client.indexOf('const applyFilters ='));
assert.doesNotMatch(helper,/fetch\(|post\(|admin-ajax|wp-json/);
const filter=client.slice(client.indexOf('const applyFilters ='),client.indexOf("search?.addEventListener"));
assert.doesNotMatch(filter,/fetch\(|post\(|admin-ajax|wp-json/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.149.0 Adventure Prep Organizer passed');
