import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/offline-mode.js');
const css=read('assets/css/offline-adventure-manager.css');
assert.match(bootstrap,/Version:\s*5\.1(?:4[5-9]|[5-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:4[5-9]|[5-9]\d)\.\d+'\)/);
assert.match(offline,/response\.headers\.get\('X-TNG-Offline-Safe'\)!=='1'/);
assert.match(offline,/type\.toLowerCase\(\)\.includes\('text\/html'\)/);
assert.match(offline,/if\(!size\)\{issues\+\+;continue;\}/);
assert.match(offline,/healthyCount:urls\.length,issues,urls,bytes/);
assert.match(client,/has-integrity-issues/);
assert.match(client,/verified public screen/);
assert.match(client,/need\$\{issues === 1 \? 's' : ''\} repair/);
assert.match(client,/Reconnect, then refresh this pack from Saved Adventures/);
assert.match(client,/issuePacks/);
assert.match(css,/has-integrity-issues/);
const libraryBlock=offline.slice(offline.indexOf('const adventureLibrary='),offline.indexOf('const clearAdventureLibrary='));
assert.doesNotMatch(libraryBlock,/fetch\(|cache\.delete|caches\.delete/);
assert.doesNotMatch(client,/admin-ajax|wp-json|setInterval|Notification/);
console.log('TN Game OS 5.145.0 Offline Adventure Integrity Check passed');
