import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.1(?:5[4-9]|[6-9]\d)\.\d+/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.1(?:5[4-9]|[6-9]\d)\.\d+'\)/);
assert.equal((module.match(/data-tng-prep-filter="[^"]+" aria-pressed="false"/g)||[]).length,3);
assert.match(client,/const prepFilters = prepOverview \? \[\.\.\.prepOverview\.querySelectorAll\('\[data-tng-prep-filter\]'\)\] : \[\]/);
assert.match(client,/const syncFilterControls = \(\) =>/);
assert.match(client,/item\.dataset\.tngAdventureFilter === selectedFilter/);
assert.match(client,/item\.dataset\.tngPrepFilter === selectedFilter/);
assert.equal((client.match(/syncFilterControls\(\);/g)||[]).length,5);
assert.match(css,/prep-metrics button\[aria-pressed="true"\]/);
const helper=client.slice(client.indexOf('const syncFilterControls ='),client.indexOf('const updateCardLaunchStatus ='));
assert.doesNotMatch(helper,/post\(|fetch\(|localStorage|\.click\(\)/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.154.0 Active Prep Filter State passed');
