import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.118\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.118\.0'\)/);
assert.match(adventure,/data-tng-plan-share>Share plan/);
assert.match(client,/event\.target\.closest\('\[data-tng-plan-share\]'\)/);
assert.match(client,/navigator\.share/);
assert.match(client,/navigator\.clipboard/);
assert.match(client,/window\.location\.origin/);
assert.match(client,/\.tng-adventure-card__stops span/);
const shareBlock=client.slice(client.indexOf("const share ="),client.indexOf("const start ="));
assert.match(shareBlock,/navigator\.share\(\{title, text\}\)/);
assert.doesNotMatch(shareBlock,/plan_id|dataset\.planId|recap|progress/);
assert.doesNotMatch(client,/operation:'share'/);
console.log('TN Game OS 5.118.0 Private-Safe Adventure Sharing checks passed');
