import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.152\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.152\.0'\)/);
assert.match(module,/<option value="prep">Prep priority<\/option>/);
assert.match(client,/const allowedSorts = \['recent','prep','date','title','status'\]/);
assert.match(client,/sort\?\.value === 'prep'/);
assert.match(client,/aUpcoming \? \(aLaunch < 10 \? 0 : 1\)/);
assert.match(client,/bUpcoming \? \(bLaunch < 10 \? 0 : 1\)/);
assert.match(client,/if \(dateOrder !== 0\) return dateOrder/);
assert.match(client,/if \(aRank === 0 && aLaunch !== bLaunch\) return aLaunch - bLaunch/);
const prepSort=client.slice(client.indexOf("if (sort?.value === 'prep')"),client.indexOf("if (sort?.value === 'date')"));
assert.doesNotMatch(prepSort,/post\(|fetch\(|checked\s*=|\.click\(\)/);
assert.match(client,/localStorage\.setItem\(preferenceKey, JSON\.stringify\(\{filter:selectedFilter,sort:sort\?\.value/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.152.0 Adventure Prep Priority Sorting passed');
