import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.125\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.125\.0'\)/);
assert.match(adventure,/data-tng-plan-schedule/);
assert.match(adventure,/name="planned_date"/);
assert.match(adventure,/data-tng-plan-clear-date/);
assert.match(adventure,/\$operation === 'schedule'/);
assert.match(adventure,/checkdate\(/);
assert.match(adventure,/\$planned_date < wp_date\('Y-m-d'\)/);
assert.match(adventure,/Restore this adventure before scheduling it/);
assert.match(adventure,/unset\(\$copy\['archived_at'\], \$copy\['planned_date'\]\)/);
assert.match(client,/operation:'schedule'/);
assert.match(client,/data-tng-plan-clear-date/);
assert.match(css,/tng-adventure-card__planned/);
assert.match(css,/tng-adventure-card__schedule/);
assert.doesNotMatch(client,/setInterval|Notification|serviceWorker/);
console.log('TN Game OS 5.125.0 Private Adventure Scheduling checks passed');
