import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.141\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.141\.0'\)/);
assert.match(offline,/const verifiedTime=Date\.parse\(verifiedAt\)/);
assert.match(offline,/Date\.now\(\)-verifiedTime>604800000/);
assert.match(offline,/stale:saved\.length>0&&\(!Number\.isFinite\(verifiedTime\)/);
assert.match(client,/info\?\.stale === true/);
assert.match(client,/needs-refresh/);
assert.match(client,/Refresh recommended/);
assert.match(client,/!current \? 'Update' : 'Refresh'/);
assert.match(css,/tng-adventure-card__offline\.needs-refresh/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.141.0 Offline Adventure Refresh Guidance checks passed');
