import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const module=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.155\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.155\.0'\)/);
assert.match(module,/data-tng-library-status aria-live="polite"/);
assert.match(client,/const launchReadyStatusFor = \(card, previousCount, fallback\) =>/);
assert.match(client,/previousCount < 10 && launchCountFor\(card\) === 10/);
assert.match(client,/All 10 preparation checks are complete/);
assert.equal((client.match(/const previousLaunchCount = launchCountFor\(card\);/g)||[]).length,2);
assert.equal((client.match(/launchReadyStatusFor\(card,previousLaunchCount,data\.message\)/g)||[]).length,2);
const helper=client.slice(client.indexOf('const launchReadyStatusFor ='),client.indexOf('const nextIncompleteCheckFor ='));
assert.match(helper,/card\.querySelector\('\[data-plan-title\]'\)/);
assert.match(helper,/return fallback \|\| 'Checklist updated\.'/);
assert.doesNotMatch(helper,/post\(|fetch\(|localStorage|\.click\(|checked\s*=/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.155.0 Private Launch-Ready Confirmation passed');
