import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.122\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.122\.0'\)/);
assert.match(adventure,/PLAN_LIBRARY_LIMIT = 12/);
assert.match(adventure,/PLAN_ARCHIVE_LIMIT = 24/);
assert.match(adventure,/data-tng-adventure-library__capacity|tng-adventure-library__capacity/);
assert.match(adventure,/Saved Adventures is full\. Archive one active plan before saving another/);
assert.match(adventure,/Saved Adventures is full\. Archive an active plan before making a copy/);
assert.match(adventure,/Active Saved Adventures is full\. Archive one plan before restoring/);
assert.doesNotMatch(adventure,/array_slice\(\$library/);
const capacityCheck=adventure.indexOf("code'=>'library_full'");
const merge=adventure.indexOf('TNG_Trip_Data::merge');
assert.ok(capacityCheck > -1 && merge > capacityCheck,'capacity check must happen before Trips changes');
assert.match(css,/\.tng-adventure-library__capacity/);
console.log('TN Game OS 5.122.0 Saved Adventure Capacity Safety checks passed');
