import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const offline=read('tn-game-offline-mode.php');
const client=read('assets/js/saved-adventures.js');
assert.match(bootstrap,/Version:\s*5\.140\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.140\.0'\)/);
assert.match(offline,/const ADVENTURE_META_CACHE='tng-adventure-pack-meta-v1'/);
assert.match(offline,/const ADVENTURE_META_ORIGIN='https:\/\/tn-game\.device\.invalid\/'/);
assert.match(offline,/const adventureMetaUrl=id=>/);
assert.match(offline,/new URL\('offline-pack\/'\+id,ADVENTURE_META_ORIGIN\)/);
assert.match(offline,/const adventureMeta=async id/);
assert.match(offline,/const setAdventureMeta=async\(id,value\)/);
assert.match(offline,/verifiedAt:typeof metadata\.verifiedAt==='string'/);
assert.match(offline,/setAdventureMeta\(id,\{verifiedAt:new Date\(\)\.toISOString\(\),count:fresh\.length\}\)/);
assert.match(offline,/metadata\.delete\(adventureMetaUrl\(id\)\)/);
const saveBlock=offline.slice(offline.indexOf("if(data.type==='TNG_ADVENTURE_PACK_SAVE'"));
assert.ok(saveBlock.indexOf('await writeEntries(liveName,fresh)')<saveBlock.indexOf('await setAdventureMeta'));
assert.match(client,/verifiedDate/);
assert.match(client,/` · verified \$\{/);
assert.match(client,/\? 'today' : verifiedDate\.toLocaleDateString/);
assert.match(client,/toLocaleDateString/);
assert.doesNotMatch(offline,/addEventListener\(['"]sync['"]/);
assert.doesNotMatch(client,/setInterval|Notification/);
console.log('TN Game OS 5.140.0 Offline Adventure Verification Date checks passed');
