import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../experiences/wordpress/tn-game-os/',import.meta.url);
const read=path=>fs.readFileSync(new URL(path,root),'utf8');
const bootstrap=read('tn-game-os.php');
const adventure=read('app/Modules/Destinations/class-adventure-ai.php');
const client=read('assets/js/saved-adventures.js');
const css=read('assets/css/saved-adventures.css');
assert.match(bootstrap,/Version:\s*5\.121\.0/);
assert.match(bootstrap,/define\('TNG_OS_VERSION','5\.121\.0'\)/);
assert.match(adventure,/data-tng-adventure-filter="archived"/);
assert.match(adventure,/data-tng-plan-archive="archive"/);
assert.match(adventure,/data-tng-plan-archive="restore"/);
assert.match(adventure,/\$library\[\$index\]\['archived_at'\] = time\(\)/);
assert.match(adventure,/unset\(\$library\[\$index\]\['archived_at'\]\)/);
assert.match(adventure,/Finish or replace the active adventure before archiving it/);
assert.doesNotMatch(adventure,/delete_user_meta\([^\n]*PLAN_LIBRARY_META/);
assert.match(client,/window\.confirm\('Archive this Saved Adventure/);
assert.match(client,/card\.dataset\.planState !== 'archived'/);
assert.match(css,/\.tng-adventure-card\.is-archived/);
console.log('TN Game OS 5.121.0 Reversible Adventure Archive checks passed');
