<?php
/**
 * Plugin Name: TN Game OS
 * Plugin URI: https://thetngame.com
 * Description: Modular tourism operating system for Traveler listings, trails, food, maps, Explorer progression, reusable assets, destinations, and developer tools.
 * Version: 5.69.0
 * Author: The TN Game
 * Text Domain: tn-game-os
 */
if (!defined('ABSPATH')) exit;
define('TNG_OS_VERSION','5.69.0');
define('TNG_OS_FILE',__FILE__);define('TNG_OS_PATH',plugin_dir_path(__FILE__));define('TNG_OS_URL',plugin_dir_url(__FILE__));
require_once TNG_OS_PATH.'app/Core/class-module-interface.php';require_once TNG_OS_PATH.'app/Core/class-container.php';require_once TNG_OS_PATH.'app/Core/class-plugin.php';
require_once TNG_OS_PATH.'app/Modules/Frontend/class-gameplay-notifications.php';require_once TNG_OS_PATH.'app/Modules/Frontend/class-mobile-session-recovery.php';
foreach(['class-destination-intelligence-center.php','class-destination-health-dashboard.php','class-destination-ai-profiles.php','class-smart-recommendation-engine.php','class-explore-nearby-widget.php','class-smart-day-planner.php','class-my-trip-workspace.php','class-personalized-trip-builder.php','class-live-trip-optimizer.php','class-live-trip-companion.php','class-multi-stop-route-navigator.php','class-active-trip-mode.php','class-trip-completion-rewards.php','class-past-trips-journal.php','class-trip-explorer-integration.php','class-explorer-journal.php','class-explorer-timeline-bridge.php','class-public-explorer-profile.php','class-explorer-profile-settings.php','class-explorer-showcase.php','class-explorer-discovery.php','class-explorer-network-intelligence.php','class-coordinate-intelligence.php','class-coordinate-quality-controls.php','class-coordinate-source-resolver.php','class-knowledge-graph-core.php','class-knowledge-graph-inspector.php'] as $f)require_once TNG_OS_PATH.'app/Modules/Destinations/'.$f;
foreach(['tn-game-checkpoint-compat.php','tn-game-developer-test-report.php','tn-game-developer-collapse.php','tn-game-test-certification.php','tn-game-game-audit.php','tn-game-runtime-qa.php','tn-game-gameplay-ui-milestone.php','tn-game-game-session-lifecycle.php','tn-game-game-session-ownership.php','tn-game-player-state-polish.php','tn-game-game-completion-sync.php','tn-game-game-completion-handoff.php','tn-game-game-explorer-integration.php','tn-game-progression-milestones.php','tn-game-progression-profile-bridge.php','tn-game-explorer-normalization.php','tn-game-live-top-sight-visits.php','tn-game-trail-top-sights.php','tn-game-trail-gpx-intelligence.php','tn-game-trail-elevation-profile.php','tn-game-trail-top-sight-cards.php','tn-game-category-progression.php','tn-game-social-intelligence.php','tn-game-social-discovery.php','tn-game-social-pattern-intelligence.php','tn-game-content-idea-generator.php','tn-game-content-production.php','tn-game-instagram-browser.php','tn-game-instagram-capture.php','tn-game-content-calendar.php','tn-game-content-campaigns.php','tn-game-content-campaign-integration.php','tn-game-content-pillars.php','tn-game-content-signal-fusion.php','tn-game-content-auto-planner.php','tn-game-content-storyline.php'] as $f)require_once TNG_OS_PATH.$f;
register_activation_hook(__FILE__,['TNG_OS\\Core\\Plugin','activate']);register_deactivation_hook(__FILE__,['TNG_OS\\Core\\Plugin','deactivate']);add_action('plugins_loaded',static function(){TNG_OS\Core\Plugin::instance()->boot();},5);
add_action('plugins_loaded',static function(){$container=new TNG_OS\Core\Container();$modules=[new TNG_OS\Modules\Frontend\Gameplay_Notifications(),new TNG_OS\Modules\Frontend\Mobile_Session_Recovery(),new TNG_OS\Modules\Destinations\Destination_Intelligence_Center(),new TNG_OS\Modules\Destinations\Destination_Health_Dashboard(),new TNG_OS\Modules\Destinations\Destination_AI_Profiles(),new TNG_OS\Modules\Destinations\Smart_Recommendation_Engine(),new TNG_OS\Modules\Destinations\Explore_Nearby_Widget(),new TNG_OS\Modules\Destinations\Smart_Day_Planner(),new TNG_OS\Modules\Destinations\My_Trip_Workspace(),new TNG_OS\Modules\Destinations\Personalized_Trip_Builder(),new TNG_OS\Modules\Destinations\Live_Trip_Optimizer(),new TNG_OS\Modules\Destinations\Live_Trip_Companion(),new TNG_OS\Modules\Destinations\Multi_Stop_Route_Navigator(),new TNG_OS\Modules\Destinations\Active_Trip_Mode(),new TNG_OS\Modules\Destinations\Trip_Completion_Rewards(),new TNG_OS\Modules\Destinations\Past_Trips_Journal(),new TNG_OS\Modules\Destinations\Trip_Explorer_Integration(),new TNG_OS\Modules\Destinations\Explorer_Journal(),new TNG_OS\Modules\Destinations\Explorer_Timeline_Bridge(),new TNG_OS\Modules\Destinations\Public_Explorer_Profile(),new TNG_OS\Modules\Destinations\Explorer_Profile_Settings(),new TNG_OS\Modules\Destinations\Explorer_Showcase(),new TNG_OS\Modules\Destinations\Explorer_Discovery(),new TNG_OS\Modules\Destinations\Explorer_Network_Intelligence(),new TNG_OS\Modules\Destinations\Coordinate_Intelligence(),new TNG_OS\Modules\Destinations\Coordinate_Quality_Controls(),new TNG_OS\Modules\Destinations\Coordinate_Source_Resolver(),new TNG_OS\Modules\Destinations\Knowledge_Graph_Core(),new TNG_OS\Modules\Destinations\Knowledge_Graph_Inspector()];foreach($modules as $module){$module->register($container);$module->boot($container);}},6);
